language: php
php:
  - '7.1'
install:
- phpenv rehash
- travis_retry composer self-update
- travis_retry composer require satooshi/php-coveralls "^1" --no-update --dev
- travis_retry composer install
script:
- phpunit -c phpunit.xml.dist
cache:
  apt: true
  directories:
  - vendor
